kind: pipeline
name: default
steps:

  - name: dependancies
    image: ethicaljobs/composer-prestissimo
    commands: 
      - 'composer install --prefer-dist --ignore-platform-reqs'
  
  - name: test
    image: php:7.2-cli-alpine
    commands: 
      - 'php vendor/bin/phpunit'

  - name: notify-slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: deployments
