kind: pipeline
name: default

steps:

  - name: dependancies
    image: composer
    commands: ['composer install --prefer-dist --ignore-platform-req']
  
  - name: test
    image: php:7.2-cli-alpine
    commands: ['./vendor/bin/phpunit']

  - name: publish
    image: byrnedo/alpine-curl
    commands: [ 'curl -XPOST -H"content-type:application/json" "https://packagist.org/api/update-package?username=andrewmclagan&apiToken=2cmy6xog4hs0kogk4ccg" -d''{"repository":{"url":"https://github.com/ethical-jobs/sdk-php"}}''' ]
    when:
      event: [ tag ]

  - name: notify-slack
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: deployments

